ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG EXTRA_PYPI_INDEX=https://pypi.org/simple

COPY elasticai_api/requirements.txt /requirements.txt
RUN python -m pip install -r /requirements.txt \
        --extra-index-url=$EXTRA_PYPI_INDEX \
        && rm /requirements.txt