ARG BASE_IMAGE
FROM ${BASE_IMAGE}
ARG EXTRA_PYPI_INDEX=https://pypi.org/simple

WORKDIR /

COPY elasticdl/docker/bashrc /etc/bash.bashrc
RUN chmod a+rx /etc/bash.bashrc

# Copy model zoo
COPY model_zoo /model_zoo
RUN python -m pip install --quiet -r /model_zoo/requirements.txt \
        --extra-index-url=${EXTRA_PYPI_INDEX}

# Install ElasticDL packages
COPY build/elasticai_api*.whl /
RUN pip install /*.whl --extra-index-url=${EXTRA_PYPI_INDEX} && rm /*.whl